version: 0.2

phases:
  install:
    commands:
      - echo Installing Serverless...
      - npm install -g serverless
  pre_build:
    commands:
      - echo Installing backend dependencies...
      # - cd backend-serverless/ && npm install
      - echo Installing frontend dependencies...
      - cd /frontend-serverless/ && npm install
  build:
    commands:
      - echo Deploying serverless backend
      - cd /backend-serverless/ && sls deploy
      - echo Deploying serverless frontend
      - cd /frontend-serverless/ && serverless
  post_build:
    commands:
      - echo Deployment completed on `date`
