# Deploys both front and backend serverless projects
# Note: Eventually split into two buildspec.yml files and run separate codebuild workflows as project grows larger
# Free tier only includes one build project

version: 0.2

cache:
  paths:
    - node_modules
    - frontend-serverless/node_modules
    - backend-serverless/node_modules

phases:
  install:
    commands:
      - echo Installing Serverless...
      - npm install -g serverless
  pre_build:
    commands:
      - echo Installing frontend dependencies...
      - cd frontend-serverless && npm install
      - echo Installing backend dependencies...
      - cd .. && cd backend-serverless && npm install
  build:
    commands:
      - echo Deploying serverless backend...
      - cd .. && cd backend-serverless && serverless deploy
      - echo Deploying serverless frontend...
      - cd .. && cd frontend-serverless && serverless
  post_build:
    commands:
      - echo Deployment completed on `date`
