service: rsvp-serverless-backend

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-domain-manager

custom:
  secrets: ${file(secrets.json)}
  allowedHeaders:
    - Accept
    - Content-Type
    - Content-Length
    - Authorization
    - X-Amz-Date
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
  customDomain:
    domainName: api.carolandarthur.com
    basePath: "v1"
    stage: ${self:provider.stage}
    certificateName: carolandarthur.com
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: prod
  memorySize: 128
  timeout: 5
  endpointType: regional
  environment:
    GUESTS_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    EMAIL: ${self:custom.secrets.EMAIL}
    DOMAIN: ${self:custom.secrets.DOMAIN}
    GH_ACCESS_TOKEN: ${self:custom.secrets.GH_ACCESS_TOKEN}
    GH_USERNAME: ${self:custom.secrets.GH_USERNAME}
    MAILGUN_APIKEY: ${self:custom.secrets.MAILGUN_APIKEY}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:ListStreams
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.GUESTS_TABLE}"
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: "*"

functions:
  stream-trigger:
    handler: lambda/stream-trigger.handler
    description: DynamoDB Stream SES Trigger
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - GuestsTable
              - StreamArn
  post-gitstatus:
    handler: lambda/post-gitstatus.handler
    description: Post pipeline execution state to GitHub
    role: arn:aws:iam::307030026322:role/service-role/git-commit-status-role-l9oj1grx
    events:
      - cloudwatchEvent:
          name: git-codepipeline-event-rule
          description: Codepipeline event feeds state into lambda to post status to GitHub for commit status badge
          event:
            source:
              - aws.codepipeline
            detail-type:
              - CodePipeline Stage Execution State Change
            detail:
              state:
                - FAILED
                - RESUMED
                - SUCCEEDED
                - CANCELED
                - STARTED

  add-guest:
    handler: api/add-guest.handler
    description: POST /guest
    events:
      - http:
          path: guest
          method: post
          cors: true
  get-guest:
    handler: api/get-guest.handler
    description: GET /guest/{email}
    events:
      - http:
          path: guest/{email}
          method: get
          cors: true
  get-guests:
    handler: api/get-guests.handler
    description: GET /guests
    events:
      - http:
          path: guests
          method: get
          cors: true

resources:
  Resources:
    GuestsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.GUESTS_TABLE}
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: email
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
