service: rsvp-serverless-backend

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  allowedHeaders:
    - Accept
    - Content-Type
    - Content-Length
    - Authorization
    - X-Amz-Date
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
    # - app_user_id
    # - app_user_name

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: prod
  memorySize: 128
  timeout: 5
  endpointType: regional
  environment:
    GUESTS_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.GUESTS_TABLE}"

functions:
  add-user:
    handler: api/add-user.handler
    description: POST /user
    events:
      - http:
          path: user
          method: post
          cors:
            origin: "*"
            headers: ${self:custom.allowedHeaders}

  get-user:
    handler: api/get-user.handler
    description: GET /user/u/{user_id}
    events:
      - http:
          path: user/u/{user_id}
          method: get
          cors:
            origin: "*"
            headers: ${self:custom.allowedHeaders}
  get-users:
    handler: api/get-users.handler
    description: GET /users
    events:
      - http:
          path: users
          method: get
          cors:
            origin: "*"
            headers: ${self:custom.allowedHeaders}

resources:
  Resources:
    GuestsTable:
      Type: AWS::DynamoDB::Table
      # DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.GUESTS_TABLE}
        AttributeDefinitions:
          # - AttributeName: user_id
          #   AttributeType: S
          # - AttributeName: guest_id
          #   AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
          # - AttributeName: first_name
          #   AttributeType: S
          # - AttributeName: last_name
          #   AttributeType: S
          # - AttributeName: guest_first
          #   AttributeType: S
          # - AttributeName: guest_last
          #   AttributeType: S
          # - AttributeName: coming
          #   AttributeType: S
          # - AttributeName: special_requests
          #   AttributeType: S
        KeySchema:
          # - AttributeName: user_id
          #   KeyType: HASH
          - AttributeName: email
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
